version: '3'
services:
  db:
    image: mysql:latest
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  app:
    build: .
    links:
      - db
    ports:
      - "8002"